### ISSUE TITLE
ログインに関する問題

### ISSUE THREAD

**Issue by Negima1072** [kairi003/nicolive-dl#3]
issue立て失礼します。
現状ニコニコでは二段階認証によるログインがサポートされており、それを有効化したアカウントでは本ツールにログインできない問題があります。
よって、二段階認証に対応する、もしくはChromeやFirefoxからクッキー情報を取ってこれるような機能を追加してほしいです。
また、何打もEmail/Passでログインをすると、ほかブラウザのログインが解除されてしまうので、一度ログインしたらクッキー情報をテキストファイルなどで保管して欲しいです。

また直接関係はないですが、以下のツイートで告知されているようにニコ生のAPIを共有するSlackがあるので、参加してみてはいかがでしょうか。OAuthでの認証も使えるようになります。

https://twitter.com/nico_nico_talk/status/1351448521409368064?s=20&t=Z5G_XNxSUHnGs7NrXFSlNQ

**Comment by kairi003** [comment]
Issueありがとうございます。
Cookieでのログインにつきましては余裕のある時に実装してみます。

> ニコ生のAPIを共有するSlack

そんなものがあるのですね…こちらも後で確認してみます。
