### ISSUE TITLE
ダウンロードが開始されない不具合

### ISSUE THREAD

**Issue by tokiyui** [kairi003/nicolive-dl#8]
タイトルの通り、アカウント名・パスワード・動画IDを入力しても何も起こりません。

**Comment by kairi003** [comment]
~~ニコニコもニコ生も新バージョンでプロトコル変えたかもですね
対応する予定はないのでこのリポジトリはアーカイブします~~

**Comment by kairi003** [comment]
一応手元では動作することを確認しました #9
